### ISSUE TITLE
how to config and build?

### ISSUE THREAD

**Issue by sonygod** [darmie/linc_uv#3]
I got this error;

        Error: In file included from include/Foo.h:11:0,
                        from ./src/Test.cpp:5:
        /root/linc_uv/linc/linc_uv.h:5:10: fatal error: /root/linc_uv/test/cpp/obj/linux64/__pch/haxe/hxcpp.h: No such file or directory
        #include <hxcpp.h>
                ^~~~~~~~~
        compilation terminated.
        Error: Build failed

I also install hxcpp with git version ,but still not work.

**Comment by darmie** [comment]
I'll investigate

**Comment by darmie** [comment]
@sonygod your solution in https://github.com/darmie/linc_uv/issues/2 may have fixed this problem for Linux. I just tested in Alpine Linux with `-D NO_PRECOMPILED_HEADERS` and it works fine. Without it, it breaks. This was not required on Mac OS. 

Please confirm if you are still facing the same issues.

Here's my Dockerfile if it helps

```Dockerfile
FROM haxe:4.1.2-alpine

COPY ./ /project

WORKDIR /project/test

RUN ls /project

RUN apk upgrade && apk add build-base

RUN yes | haxelib install all

RUN haxe build.hxml

CMD ["./cpp/Test"]
```

**Comment by sonygod** [comment]
I sorry,I use centos or ubuntu to build you project,but fail.I will try to find out what's wrong ...

BTW.why you have to link hxcpp.h ?

edit

which libuv you use?

I got this error 

       obj/linux64/ee7ccce9_sysinfo-memory.o: In function `uv_get_free_memory':
    sysinfo-memory.c:(.text+0x0): multiple definition of `uv_get_free_memory'
    obj/linux64/ee7ccce9_linux-core.o:linux-core.c:(.text+0x1ac0): first defined here
    obj/linux64/ee7ccce9_sysinfo-memory.o: In function `uv_get_total_memory':
    sysinfo-memory.c:(.text+0x50): multiple definition of `uv_get_total_memory'
    obj/linux64/ee7ccce9_linux-core.o:linux-core.c:(.text+0x1b30): first defined here
    obj/linux64/ee7ccce9_sysinfo-loadavg.o: In function `uv_loadavg':
    sysinfo-loadavg.c:(.text+0x0): multiple definition of `uv_loadavg'
    obj/linux64/ee7ccce9_linux-core.o:linux-core.c:(.text+0x1bb0): first defined here
    obj/linux64/ee7ccce9_core.o: In function `uv_os_uname':
    core.c:(.text+0x1efc): undefined reference to `uv__strscpy'
    core.c:(.text+0x1f19): undefined reference to `uv__strscpy'
    core.c:(.text+0x1f44): undefined reference to `uv__strscpy'
    core.c:(.text+0x1f61): undefined reference to `uv__strscpy'
    obj/linux64/3f080df5_uv-common.o: In function `uv_err_name_r':
    uv-common.c:(.text+0x30b): undefined reference to `uv__strscpy'
    obj/linux64/3f080df5_uv-common.o:uv-common.c:(.text+0x380): more undefined references to `uv__strscpy' follow
    collect2: error: ld returned 1 exit status
    Error: Build failed

**Comment by sonygod** [comment]
finally,I found out what's wrong.

you have to  git checkout in sub folder 

      git submodule update --init --recursive

thanks @darmie
