### ISSUE TITLE
[question] will you make full complete  examples?

### ISSUE THREAD

**Issue by sonygod** [darmie/linc_uv#5]
will you make full complete examples?

current in test folder  only have 

client connect  server  , and server send message to the client

where is the client receive function? and sent and write to the server function?

how about adding more examples about udp？

**Comment by darmie** [comment]
@sonygod the original goal is to develop a NodeJS server API around it. But for now I don't have the time to do it. 

If you could get some examples from LibUV repository and try to replicate it in Haxe, it would be nice to see what results you are getting, and hopefully submit a pull request of your examples.

**Comment by sonygod** [comment]
[link](https://github.com/sonygod/websockethl/tree/hxcpp)
