### ISSUE TITLE
Unknown identifier : loop

### ISSUE THREAD

**Issue by sonygod** [darmie/linc_uv#6]
I got this error 

    uv/Fs.hx:19: characters 76-80 : Unknown identifier : loop
    uv/Fs.hx:19: characters 76-80 : ... For function argument 'loop'
    uv/Fs.hx:20: characters 65-69 : Unknown identifier : loop
    uv/Fs.hx:20: characters 65-69 : ... For function argument 'loop'
    uv/Fs.hx:21: characters 84-88 : Unknown identifier : loop
    uv/Fs.hx:21: characters 84-88 : ... For function argument 'loop'
    uv/Fs.hx:22: characters 67-71 : Unknown identifier : loop
    uv/Fs.hx:22: characters 67-71 : ... For function argument 'loop'
    uv/Fs.hx:23: characters 86-90 : Unknown identifier : loop
    uv/Fs.hx:23: characters 86-90 : ... For function argument 'loop'

should be 

	public inline function open(req, path, flags, mode, cb) return Uv.fs_open(Loop.DEFAULT.asRaw(),req, path, flags, mode, cb);
	public inline function close(req, file, cb) return Uv.fs_close(Loop.DEFAULT.asRaw(),req,  file, cb);
	public inline function read(req, file, bufs, nbufs, offset, cb) return Uv.fs_read(Loop.DEFAULT.asRaw(),req,  file, bufs, nbufs, offset, cb);
	public inline function unlink(req, path, cb) return Uv.fs_unlink(Loop.DEFAULT.asRaw(),req, path, cb);
	public inline function write(req, file, bufs, nbufs, offset, cb) return Uv.fs_write(Loop.DEFAULT.asRaw(),req, file, bufs, nbufs, offset, cb);

**Comment by darmie** [comment]
@sonygod linc_uv is generally work in progress and has not been used in any project yet. 

Could you post a sample of the code you are running? So that I can reproduce it on my end. 

Also, it may worth trying to implement it side by side with C code and see if you get the same error.

**Comment by sonygod** [comment]
I try to use lib_uv user for my websocket framework . [link](https://github.com/sonygod/websockethl/tree/hxcpp)

I'll post here if I finish.

edit

finish  first version of websocket with libuv  [link](https://github.com/sonygod/websockethl/tree/hxcpp)
